### PR TITLE
adds php 7.2 to travis

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bluebaroncanada** [comment]
I'm worried this commit or commits like it could cause other logical statements to trigger.  For example: null or truth checks.

**Comment by bluebaroncanada** [comment]
It might not just be this code that's affected by this change, too.

**Comment by bluebaroncanada** [comment]
Never mind.  It shouldn't be an issue.  My apologies.

**Comment by bluebaroncanada** [comment]
Err.  Actually it is if `$a=[]; $a===null;`

**Comment by bshaffer** [comment]
You bring up a good point. `$server->getResponseType` and `$server->getGrantType` will be returning differently with this change. It may be time we rename `master` to `v1-master`, and rename `develop` to `master` and merge in the changes from the `v2` branch.

**Comment by bshaffer** [comment]
@bluebaroncanada This change is very benign. We should look into moving to `v2.0` soon, however!

**Pull request merged**
