### PR TITLE
Car 7462 set short expiration time for refresh token

### PR DESCRIPTION
**Pull request by jdubey77**
Changed the REFRESH_LIFETIME key value from 604,800 to 3900.

### CODE REVIEW

**Review by myerscb — CHANGES_REQUESTED** [review]
This pull request needs to be against carepointe_oauth branch not master

**Comment by jdubey77** [comment]
@myerscb - I am unable to find carepointe_oauth base branch.

**Comment by jdubey77** [comment]
> This pull request needs to be against carepointe_oauth branch not master

 @myerscb  While editing the pull request I am not able to find carepointe_oauth branch. Please guide me.

**Comment by myerscb** [comment]
https://github.com/arkoshealth/oauth2-server-php/tree/carepointe_oauth

**Comment by jdubey77** [comment]
I am closing the pull request due to some issue while creating branch.

**Comment by jdubey77** [comment]
I am colsing this pull request due to some issue while creating branch.

**Pull request closed without merging**
