### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by afilippov1985**

### CODE REVIEW

**Comment by afilippov1985** [comment]
Travis is broken again

**Comment by afilippov1985** [comment]
[Here, in comparison](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/JwtBearer.php#L131) $jwt['exp'] casts to int, аnd overflow occurs.
```php
$d = 99999999900;
$t = time();
$b = ($d <= $t);
$i = (int)$d;

var_dump($d, $t, $b, $i);
//double(99999999900) int(1453980111) bool(false) int(1215752092) 
```

**Comment by afilippov1985** [comment]
May be we should check that `access_token` key exists in array.

**Comment by afilippov1985** [comment]
ping @bshaffer

**Comment by bshaffer** [comment]
We should make this PR to `master` as the `develop` branch is no longer being used.

Also, the tests are passing as-is, so I'm not entirely sure what this fixes.

**Comment by afilippov1985** [comment]
I'll make a few smaller PRs.

**Pull request closed without merging**
