### PR TITLE
PHPDoc improvements and type hinting of variables.

### PR DESCRIPTION
**Pull request by Wilt**
Here some suggestions for improving the PHPDoc in the `OAuth2\Controller\TokenController.php`.
Currently in my php code editor it looked all a bit messy. Proper PHPDoc and variable declaration can really help understanding the working of this OAuth2 module.
Right now I only change this controller, but if you merge this pull request I am very willing to also spend time updating/improving the PHPDoc of any other files in the repo.

### CODE REVIEW

**Comment by bshaffer** [comment]
Hey, this looks great! Which code editor are you using?

**Comment by Wilt** [comment]
Hello Brent,
I am happy you like my changes. I use PHP storm : https://www.jetbrains.com/phpstorm/
If you want I can also look at other classes later if I find some time.
Greetings,
Wilt

**Comment by bshaffer** [comment]
@Wilt I would love to see this standard for documenting implemented as standard across the library

**Comment by Wilt** [comment]
@bshaffer I finally found some time to work myself through the library and add php-docs and type hinting as in the example. I tried to be as thorough as possible and I think it is a good start. I believe it will also motivate other contributors to improve/update the php-doc even more. I did not manage to add docs to all Storage classes yet, but this can be added later. 

Hope you like it.

**Comment by bshaffer** [comment]
merged!

**Pull request closed without merging**
