### PR TITLE
#900 Removing PHP 5.4 shorthand array syntax

### PR DESCRIPTION
**Pull request by augsteyer**

### CODE REVIEW

**Comment by svycka** [comment]
then maybe add back php 5.3 to travis test matrix to be sure that everything works

**Comment by bshaffer** [comment]
Works for me, thank you!

**Comment by gmox** [comment]
out of curiosity, why support a version of PHP that's not been updating for over 2 years?

**Comment by augsteyer** [comment]
If you provide a plugin/service to a million+ online retailers out there, there is still a large number of them who have not upgraded their servers because of fears of breaking their store. One can say to not support such merchants out of principle, but that would mean losing millions of dollars. My CFO's always go for the dollars :) 

p.s. heck, we still have merchants on 5.2

**Comment by Ben-Ho** [comment]
@bshaffer do you plan on creating a new release for this fix? Currently we include your package by directly referencing the commit-hash in our projects composer.json, because we thought this would just be a matter of time. (currently no big problem as there are not many new changes in rou repo, but it gives me a bad feeling ;-) )

**Comment by Ben-Ho** [comment]
@bshaffer thank you! :-)

**Pull request merged**
