### PR TITLE
Fixed some special chars in redirect uri while GrantType/AuthCode

### PR DESCRIPTION
**Pull request by tino415**
Authorized redirect uri was containing some unencoded chars...

### CODE REVIEW

**Comment by bshaffer** [comment]
Hmm... shouldn't the decoding be done upon storage? I don't see why we would want this `url-encoded` in the database/storage...

**Comment by tino415** [comment]
I agree, this was just quick fix, i just have problem that there was unencoded url, i probably should write bug report...

**Comment by bshaffer** [comment]
Yes, let's try to fix this at the root. How did the *url-encoded* URL make it into the database in the first place?

**Comment by bshaffer** [comment]
closing until a better solution is proposed

**Pull request closed without merging**
