### PR TITLE
Fix PHPDoc

### PR DESCRIPTION
**Pull request by maxailloud**
Basically just some PHPDoc fix.

### CODE REVIEW

**Comment by bshaffer** [comment]
Dumb question, is the leading `\` necessary? I assume the answer is PHPDoc reads from the same namespace as the executing PHP code does, and since we don't have a `use` statement and we are in a different namespace, PHPDoc sees this as `\OAuth2\Controller\OAuth2\GrantType\ClientCredentials` (for [instance](https://github.com/Chargifi/oauth2-server-php/blob/5a26917d578c99e969ed0b008106af4145586475/src/OAuth2/Controller/TokenController.php#L160))

**Comment by maxailloud** [comment]
In PHPStorm not putting the leading `\` gives me an error. 
And rightfully as the class `\OAuth2\Controller\OAuth2\GrantType\ClientCredentials` doesn't exist, but `\OAuth2\GrantType\ClientCredentials` does.

**Comment by bluebaroncanada** [comment]
If you use `use`, you don't need the preceding `\`.

**Comment by maxailloud** [comment]
Yes but importing a class just for the PHPDoc is pointless.
It's just updating the namespace of the classes use in the PHPDoc to have the real namespace.

**Comment by bluebaroncanada** [comment]
Yeah.  Sorry.  I think that made some of you think that I actually care. :p

**Pull request merged**
