### PR TITLE
fixes BC issue from #571

### PR DESCRIPTION
**Pull request by bshaffer**
fixes issue noticed by @pjcdawkins

### CODE REVIEW

**Comment by pjcdawkins** [comment]
+1!

**Comment by bshaffer** [comment]
@pjcdawkins  I actually changed my mind on how to implement this - what do you think?

**Comment by pjcdawkins** [comment]
Better: more explicit and each option now does what it says it will

**Comment by guillerodriguez** [comment]
@bshaffer The Server class provides default values for both `always_issue_new_refresh_token` and `unset_refresh_token_after_use`. So even if user code only defines `always_issue_new_refresh_token` (see issue #824), the "isset" test in commit 7731601 will not catch this case (both config parameters will always be defined).

**Pull request merged**
